### ISSUE TITLE
F-Droid can't build - Java 19

### ISSUE THREAD

**Issue by licaon-kter** [Fox2Code/FoxMagiskModuleManager#323]
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportFdroidRelease'.
> Could not create task ':app:compileFdroidReleaseJavaWithJavac'.
   > Failed to calculate the value of task ':app:compileFdroidReleaseJavaWithJavac' property 'javaCompiler'.
      > No matching toolchains found for requested specification: {languageVersion=19, vendor=any, implementation=vendor-specific}.
         > No locally installed toolchains match (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1.1/userguide/toolchains.html#sub:download_repositories).
```

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4216332703#L979
ref: https://monitor.f-droid.org/builds/log/com.fox2code.mmm.fdroid/70#site-footer

And F-Droid can't install it: https://packages.debian.org/search?suite=all&arch=amd64&searchon=names&keywords=openjdk-19 :(

Is Java 17 not enough anymore?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c7d7e4e920c109af8d0e4bfd9483c349e0d05104

**Comment by androidacy-user** [comment]
We really have no intention of reverting back to a older version of java, as we test, develop, and locally build against the latest supported version of java (currently 19 due to kotlin limitations). We cannot guarantee that the code will even work on older versions.

We'd be happy to explore other solutions at the new repo https://github.com/Androidacy/MagiskModuleManager however.
