### ISSUE TITLE
Lack of install documation.

### ISSUE THREAD

**Issue by Techwolf** [Fox2Code/FoxMagiskModuleManager#63]
I did a quick look around and search. I could not find the following info.

Is this a Android app that can be sideloaded just like any other android app?  OR
Does FMMM need to be installed using Magisk plugin feature "Install from storage"?

I did look in the Magisk plugsins list and did not find FMMM, I used Magisk v23.0 that stills has the plugin repro.

A quick blurb on the readme.md on how to install or at least say if this is an app or magisk module would be nice.

**Comment by Sei-lus** [comment]
Not affiliated with the project but come on... But come on.
![Screenshot 2021-12-31 203432](https://user-images.githubusercontent.com/57790936/152712292-fb998712-9ad4-4d01-9777-0af541b41970.png)
![Screenshot 2021-12-31 205129](https://user-images.githubusercontent.com/57790936/152712294-09dee956-02cb-4264-817b-ae318f13d4f9.png)

The word app is clearly stated in the first part of the readme. The word app is on the release, and the release contains a .apk file... That may hint at the fact it is an app.

As a note: Magisk installs modules, not apps. There are some modules that come with apps that you must install separately or are loaded by the module.

**Comment by Sei-lus** [comment]
![Screenshot 2022-02-06 214344](https://user-images.githubusercontent.com/57790936/152712451-275c062e-cb50-47ab-b8e6-8e3668ccfe5e.png)
![Screenshot 2022-02-06 214318](https://user-images.githubusercontent.com/57790936/152712452-2b9cd031-2540-45d6-86c7-73f1bcd7b057.png)

Humility lesson for loading the wrong screenshots.

Right, so app is mentioned in the readme. App is mentioned in releases, .apk file at releases for installation.
Magisk installs modules and when done locally you use a .zip file.

**Comment by Techwolf** [comment]
So magisk modules are strictly a .zip file and can not be an .apk file? The magisk app always refer to them as a module or plugin, I don't remember seeing anywhere where they are only a zip file in magisk. I have never created a magisk module/plugin, so I don't know. Hence why the question. Also, I notice the source is a zip file. That could confused an users that thinks this is a magisk plugin and try to use the zip file if all magisk plugins/modules are zip files only.

**Comment by Sei-lus** [comment]
I'm not an expert that's why I didn't say the Magisk ONLY install .zip files. The zip usually contain an install script as far as I know so technically I'm very likely to be wrong if I said that it only uses .zip files.

I'm pointing that the readme declares this is an app with an .apk file twice in the 3 first lines. Beyond that, I'm saying that magisk usually call the plugins modules but that's it.

Github source files are another thing, and I personally believe that is the user can't distinguish apk, zip, sources, etc... then they shouldn't be rooting their device. Techwolf, would you consider writing a readme.md (the frontpage) for this page so Fox can copy/paste it and that way you could contribute?

**Comment by Fox2Code** [comment]
My app is an apk that can be side loaded normally.

I will clarify that in the README.md to be more explicit.
