### ISSUE TITLE
Incorrect translation of readme.md

### ISSUE THREAD

**Issue by giving-sesame** [Fox2Code/FoxMagiskModuleManager#9]
Hi, thank you for nice manager.

I noticed a minor issue. In Russian readme.md the name of your module is "Менеджер модулей Magisk компании Fox", which means: "Magisk Modules Manager by Fox Company". But as I understand, you are not a company. I would like to suggest to amend the heading in this way: "Менеджер модулей Magisk разработчика Fox2Code".

**Comment by Fox2Code** [comment]
Your are probably using the built-in translation of your web browser, because there is no such thing as a Russian README.md.

No one speaking Russian contributed to this project yet.

If you wish to translate the project you can use github pull-request feature to do so.

The folder name for russian translation would be `values-ru`, and instructions are in the README.MD

**Comment by giving-sesame** [comment]
Oh, I see. I'm sorry for this mistake.

I'm afraid I'm not very good in translation
