### ISSUE TITLE
Download button visible even when installed

### ISSUE THREAD

**Issue by CodeSpoof** [Fox2Code/FoxMagiskModuleManager#95]
**Is your feature request related to a problem? Please describe.**

Download button still there if the module is installed and not outdated. 

**Describe the solution you'd like**

Removal of said button under described circumstances. 

**Describe alternatives you've considered**

Switch for reinstall button? 

**Additional context**

If a module is already installed, there shouldn't be a need to download it again.

**Comment by Fox2Code** [comment]
Download button will not be removed, it allow users to download modules that they already installed if they want to make backups.

It's not because you don't need something that it's not useful for someone else.

Also I only have Android Studio built-in artwork to work with, or I have to scrap the internet for new icons.
